services:
    theme_helper.listener.insert_tags:
        class: Pdir\ThemeHelperBundle\EventListener\InsertTagsListener
        public: true
        arguments:
            - "@contao.framework"

    theme_helper.listener.article_field_permissions:
        class: Pdir\ThemeHelperBundle\EventListener\ArticleFieldPermissionsListener
        public: true

    theme_helper.listener.content_field_permissions:
        class: Pdir\ThemeHelperBundle\EventListener\ContentFieldPermissionsListener
        public: true
