services:
    _defaults:
        autoconfigure: true
        autowire: true

    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ["setFramework", ["@contao.framework"]]

    Pdir\ThemeHelperBundle\:
        resource: ../src/
